import type { PlatformKnowledgeModule } from "../types.js";

export const IDENTITY_WORKSPACE_MODULES: readonly PlatformKnowledgeModule[] = [
  {
    moduleId: "platform_identity",
    category: "platform_identity",
    label: "Platform Identity",
    topicLabel: "Platform Identity",
    keywords: [
      "humanity union",
      "platform",
      "purpose",
      "transparency",
      "responsibility",
      "evidence",
      "non-violence",
      "knowledge sharing",
      "civic collaboration",
    ],
    surfaces: "all",
    content: [
      "Humanity Union is a civic collaboration platform where Participants organize Initiatives,",
      "discuss evidence, advance a public Lifecycle, and preserve outcomes for others to learn from.",
      "The platform role is to host structured participation — not to replace public institutions or cast official government votes.",
      "Core operating expectations: constructive collaboration, transparency of published records,",
      "voluntary participation, personal responsibility for published content, preference for evidence over popularity,",
      "non-violence in civic language, and knowledge sharing through the Civic Archive.",
      "Explain functionality and process; do not advertise the platform with slogans.",
    ].join(" "),
  },
  {
    moduleId: "participant_member",
    category: "participant_member",
    label: "Participant and Member",
    topicLabel: "Participant",
    keywords: [
      "participant",
      "member",
      "membership",
      "signed-in",
      "identity",
      "visitor",
      "terminology",
    ],
    surfaces: "all",
    relatedModuleIds: ["participation_representative"],
    content: [
      "Canonical terminology: Participant is the universal foundational actor identity on Humanity Union.",
      "A signed-in Participant may use Workspace tools, join Discussions, support Initiatives, accept Commitments,",
      "and collaborate when invited — Membership is not required for ordinary platform participation.",
      "Member is an earned or honorary status within the Participant identity. Membership supports continuity and recognition;",
      "it does not grant decision authority over other Participants and must never be described as a prerequisite for basic civic actions.",
      "Visitors may view many public surfaces; authenticated identity is required for personal Workspace context and Assistant sessions that use personal context.",
      "Always use Participant-first language.",
    ].join(" "),
  },
  {
    moduleId: "workspace",
    category: "workspace",
    label: "Workspace",
    topicLabel: "Workspace",
    keywords: [
      "workspace",
      "workspace home",
      "personal statistics",
      "navigation",
      "my initiatives",
      "commitments",
      "tracking",
      "assistant widget",
    ],
    surfaces: ["workspace", "initiatives", "notifications", "messages", "commitment", "tracking"],
    relatedModuleIds: ["notifications", "messages", "allies", "initiatives"],
    content: [
      "In the current Workspace model, Workspace is the signed-in home for civic work.",
      "Workspace Home orients the Participant with personal statistics, priorities, and next actions.",
      "Typical areas: Initiatives (create, review, and open Initiatives you steward or follow),",
      "Allies (Initiative collaboration relationships — not a global friendship graph),",
      "Messages (Direct Messaging and Initiative communication entry points),",
      "Authoring (Become an Author / Publishing entry for the Humanity Union Blog at /workspace/authoring),",
      "Notifications (platform and Initiative events), Commitments and Tracking (responsibility and progress),",
      "and the Humanity Union Assistant entry widget.",
      "Workspace actions depend on role and eligibility; the Assistant explains available actions without claiming to perform them.",
    ].join(" "),
  },
  {
    moduleId: "profile",
    category: "profile",
    label: "Profile and Participation Area",
    topicLabel: "Profile",
    keywords: [
      "profile",
      "participation area",
      "display name",
      "public profile",
      "biography",
      "skills",
      "professional links",
    ],
    surfaces: ["profile", "preferences"],
    relatedModuleIds: ["privacy", "participant_member"],
    content: [
      "Profile / Participation Area presents a Participant’s public civic identity.",
      "It may show display name, biography, skills, professional links, organization, location,",
      "and recent Initiatives according to privacy choices — never private message contents or credentials.",
      "The Assistant may explain what Profile sections are for and how visibility choices work,",
      "but must not invent or expose private field values that are not in authorized session context.",
    ].join(" "),
  },
  {
    moduleId: "preferences",
    category: "preferences",
    label: "Preferences",
    topicLabel: "Preferences",
    keywords: ["preferences", "settings", "language", "privacy settings", "notification settings"],
    surfaces: ["preferences", "notifications", "profile"],
    relatedModuleIds: ["privacy", "notifications"],
    content: [
      "Preferences hold personal settings for language, notifications, privacy, and presentation.",
      "Preferences never override civic eligibility rules, Lifecycle publication rules, or Safety validation.",
      "Changing Preferences affects how the Participant experiences the platform; it does not rewrite public civic records.",
    ].join(" "),
  },
];
