import type { PlatformKnowledgeModule } from "../types.js";

export const INITIATIVES_COLLABORATION_MODULES: readonly PlatformKnowledgeModule[] = [
  {
    moduleId: "initiatives",
    category: "initiatives",
    label: "Initiatives",
    topicLabel: "Initiative",
    keywords: [
      "initiative",
      "author",
      "steward",
      "draft",
      "publish",
      "ownership",
      "cover",
      "public initiative",
      "author workspace",
    ],
    surfaces: ["initiatives", "initiative", "workspace", "discussion", "analysis"],
    relatedModuleIds: ["discussion", "allies", "lifecycle_overview"],
    content: [
      "An Initiative is the sole canonical civic root on Humanity Union. Lifecycle artifacts require valid Initiative ancestry.",
      "The Author (steward) owns drafting responsibility for Author Workspace content.",
      "Draft work remains private until the Author publishes. Publish makes a version publicly visible and starts public consequences for that stage.",
      "Public Initiatives may show Discussion, support signals, cover media, Active Allies, and Lifecycle stage results according to publication state.",
      "Public/private presentation boundaries: Author Workspace is private drafting; Public Preview inspects public appearance;",
      "Public Viewer shows published results. Allies do not receive Author Workspace editing controls.",
    ].join(" "),
  },
  {
    moduleId: "discussion",
    category: "discussion",
    label: "Discussion",
    topicLabel: "Discussion",
    keywords: [
      "discussion",
      "comment",
      "helpful",
      "proposal candidate",
      "constructive",
    ],
    surfaces: ["discussion", "initiative", "analysis"],
    relatedModuleIds: ["initiatives", "collaboration", "allies"],
    content: [
      "Discussion is open civic conversation on an Initiative.",
      "Participants may contribute comments; comments may be marked Helpful, Not Helpful, or as proposal candidates for later stages.",
      "Discussion feeds Collaborative Analysis as a source of themes, evidence signals, and open questions — not as automatic truth.",
      "The Assistant helps formulate constructive contributions and clarify process; it does not invent quote attributions.",
    ].join(" "),
  },
  {
    moduleId: "collaboration",
    category: "collaboration",
    label: "Collaboration",
    topicLabel: "Collaboration",
    keywords: [
      "ready to collaborate",
      "collaboration request",
      "accept",
      "decline",
      "initiative team",
      "collaboration channel",
      "collaboration sessions",
      "shared documents",
      "group chat",
    ],
    surfaces: ["initiative", "discussion", "messages", "workspace"],
    relatedModuleIds: ["allies", "messages"],
    content: [
      "Collaboration is Initiative-scoped, not a global friendship system.",
      "Ready to Collaborate expresses interest in working with the Author on that Initiative.",
      "A collaboration request may be Accepted or Declined by the appropriate party.",
      "Accepted collaboration yields Active Ally status for that Initiative’s team context.",
      "Collaboration tools may include Direct Messaging, Initiative Group Chat / Collaboration Channel,",
      "Collaboration Sessions, and Shared Documents for coordination.",
      "These tools support work; they do not replace Lifecycle publication steps or vote on behalf of anyone.",
    ].join(" "),
  },
  {
    moduleId: "allies",
    category: "allies",
    label: "Allies and Active Allies",
    topicLabel: "Allies / Active Allies",
    keywords: [
      "active ally",
      "active allies",
      "ally",
      "allies",
      "collaborator",
      "invite to allies",
    ],
    surfaces: ["initiative", "discussion", "workspace", "messages"],
    relatedModuleIds: ["collaboration", "messages", "participant_member"],
    content: [
      "An Active Ally is a Participant collaborating with an Initiative Author on that Initiative.",
      "Ally status is earned through Ready to Collaborate and invitation/acceptance — not assumed globally.",
      "Active Allies contribute through Discussion, collaboration tools, and accepted Commitments.",
      "Active Allies do not receive Author Workspace editing controls and cannot publish on the Author’s behalf.",
      "Do not describe Allies as a platform-wide friendship or social graph.",
    ].join(" "),
  },
  {
    moduleId: "messages",
    category: "messages",
    label: "Messages",
    topicLabel: "Direct Messages",
    keywords: [
      "messages",
      "direct message",
      "direct messaging",
      "dm",
      "chat",
      "private message",
      "initiative group chat",
      "conversation",
    ],
    surfaces: ["messages", "workspace", "initiative"],
    relatedModuleIds: ["collaboration", "allies", "privacy", "notifications"],
    content: [
      "Messages cover private Direct Messaging between Participants and Initiative communication entry points",
      "(such as Initiative Group Chat / Collaboration Channel for Author and Active Allies).",
      "Message history remains in chat history. It is never sent to the Assistant automatically.",
      "Unread communication entries may appear in the Notification Center as links into Workspace Messages;",
      "those entries are not the same as Notifications about Lifecycle events, and they are not moved into Notification Archive as chat transcripts.",
      "The Assistant may explain messaging features and privacy boundaries; it must refuse to read or summarize private conversation contents.",
    ].join(" "),
  },
  {
    moduleId: "community_intelligence",
    category: "community_intelligence",
    label: "Community Intelligence",
    topicLabel: "Related Initiatives / Collaboration discovery",
    keywords: [
      "similar initiative",
      "related initiative",
      "duplicate",
      "possible duplicate",
      "complementary",
      "collaboration opportunity",
      "overlap",
      "community intelligence",
      "shared themes",
      "priority match",
    ],
    surfaces: ["initiative", "initiatives", "workspace", "analysis"],
    relatedModuleIds: ["initiatives", "collaboration", "allies", "privacy"],
    content: [
      "Community Intelligence helps Participants discover related, complementary, or possibly overlapping Initiatives and collaboration opportunities.",
      "It uses deterministic, explainable public signals only — never private messages, hidden skills, or hidden location.",
      "Relationship labels are possible_duplicate, related, or complementary. possible_duplicate never means automatic merge or suppression.",
      "Every result includes human-readable reasons answering “Why am I seeing this?”. Scores are for ordering only.",
      "The Assistant may explain Community Intelligence structured results; it must not invent related Initiatives absent from that structured result.",
      "Community Intelligence is not an engagement-maximizing recommendation engine and must not rank Participants by human worth.",
    ].join(" "),
  },
];
