import type { PlatformKnowledgeModule } from "../types.js";

function stageKnowledge(input: {
  readonly moduleId: string;
  readonly label: string;
  readonly topicLabel: string;
  readonly keywords: readonly string[];
  readonly surfaces: PlatformKnowledgeModule["surfaces"];
  readonly purpose: string;
  readonly input: string;
  readonly output: string;
  readonly authorRole: string;
  readonly participantRole: string;
  readonly assistantRole: string;
  readonly publicationMeaning: string;
  readonly nextStage: string;
  readonly relatedModuleIds?: readonly string[];
}): PlatformKnowledgeModule {
  return {
    moduleId: input.moduleId,
    category: input.moduleId === "civic_archive" ? "civic_archive" : "lifecycle",
    label: input.label,
    topicLabel: input.topicLabel,
    keywords: input.keywords,
    surfaces: input.surfaces,
    relatedModuleIds: input.relatedModuleIds,
    content: [
      `According to the current Initiative Lifecycle — ${input.label}:`,
      `Purpose: ${input.purpose}`,
      `Input: ${input.input}`,
      `Output: ${input.output}`,
      `Author role: ${input.authorRole}`,
      `Participant role: ${input.participantRole}`,
      `AI Assistant role: ${input.assistantRole}`,
      `Publication meaning: ${input.publicationMeaning}`,
      `Next stage: ${input.nextStage}`,
      "This knowledge explains the stage. Stage Intelligence instructions (separate) tell the Assistant how to help within Author Workspace drafting.",
    ].join("\n"),
  };
}

export const LIFECYCLE_PARTICIPATION_MODULES: readonly PlatformKnowledgeModule[] = [
  {
    moduleId: "lifecycle_overview",
    category: "lifecycle",
    label: "Initiative Lifecycle overview",
    topicLabel: "Initiative Lifecycle",
    keywords: [
      "lifecycle",
      "stages",
      "initiative lifecycle",
      "overview",
      "sequence",
      "ordered stages",
    ],
    surfaces: "all",
    relatedModuleIds: ["initiatives"],
    content: [
      "According to the current Initiative Lifecycle, stages advance in this order:",
      "Initiative → Discussion → Collaborative Analysis → Improvement Proposals → Revision → Petition →",
      "Decision Session → Collective Decision → Implementation Commitments → Implementation Tracking →",
      "Official Responses → Public Impact → Civic Archive.",
      "Each published stage creates a public civic record the Author remains responsible for.",
      "Stages build on earlier work; later stages must not invent earlier evidence that was never published.",
    ].join(" "),
  },
  stageKnowledge({
    moduleId: "lifecycle_initiative",
    label: "Initiative stage",
    topicLabel: "Initiative",
    keywords: ["initiative stage", "create initiative", "start initiative"],
    surfaces: ["initiative", "initiatives"],
    purpose: "Establish the civic root: problem, intent, and public identity of the Initiative.",
    input: "Author intent, title, description, metadata, optional cover media.",
    output: "A published Initiative others can find, discuss, and follow through the Lifecycle.",
    authorRole: "Drafts and publishes the Initiative; remains responsible for published wording.",
    participantRole: "May view public Initiatives, Support/Do Not Support, and join Discussion when available.",
    assistantRole: "Explain Initiative structure, drafting clarity, and Lifecycle navigation — never publish.",
    publicationMeaning: "The Initiative becomes publicly visible as the civic root.",
    nextStage: "Discussion",
    relatedModuleIds: ["initiatives", "lifecycle_overview"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_discussion",
    label: "Discussion stage",
    topicLabel: "Discussion",
    keywords: ["discussion stage"],
    surfaces: ["discussion", "initiative"],
    purpose: "Collect constructive civic conversation, evidence signals, and proposal candidates.",
    input: "Published Initiative context and Participant comments.",
    output: "Discussion record with Helpful/Not Helpful signals and proposal-marked contributions.",
    authorRole: "Hosts and moderates within platform rules; may later synthesize Discussion in Analysis.",
    participantRole: "Contribute comments; mark helpfulness; express Ready to Collaborate when offered.",
    assistantRole: "Help draft constructive comments and clarify Discussion norms — never invent quotes.",
    publicationMeaning: "Comments and signals become part of the Initiative’s public conversation record.",
    nextStage: "Collaborative Analysis",
    relatedModuleIds: ["discussion", "lifecycle_overview"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_analysis",
    label: "Collaborative Analysis",
    topicLabel: "Collaborative Analysis",
    keywords: [
      "collaborative analysis",
      "analysis",
      "evidence",
      "open questions",
      "supporting evidence",
    ],
    surfaces: ["analysis"],
    purpose: "Synthesize Discussion into evidence-aware analysis: support, risks, open questions, improvements.",
    input: "Discussion themes, proposal candidates, Initiative framing.",
    output: "Published Collaborative Analysis document sections the Author stands behind.",
    authorRole: "Drafts Analysis in Author Workspace; reviews AI suggestions; Saves → Preview → Publish.",
    participantRole: "Read published Analysis; use it to inform later proposals and decisions.",
    assistantRole: "Help separate evidence vs opinion, spot gaps, and improve clarity — never auto-publish.",
    publicationMeaning: "Analysis becomes a public synthesis others can cite in later stages.",
    nextStage: "Improvement Proposals",
    relatedModuleIds: ["lifecycle_overview", "discussion"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_proposal",
    label: "Improvement Proposals",
    topicLabel: "Improvement Proposals",
    keywords: ["improvement proposals", "proposal", "proposals"],
    surfaces: ["proposal"],
    purpose: "Capture concrete improvement options grounded in Analysis and Discussion.",
    input: "Published Analysis, Discussion proposal candidates, Initiative goals.",
    output: "Published Improvement Proposals describing optional changes.",
    authorRole: "Drafts and publishes proposals; remains responsible for claims.",
    participantRole: "Review proposals; discuss trade-offs; prepare for Revision choices.",
    assistantRole: "Help clarify options and evidence needs without choosing winners.",
    publicationMeaning: "Proposals are public options for consideration, not automatic adoption.",
    nextStage: "Revision",
    relatedModuleIds: ["lifecycle_overview", "lifecycle_analysis"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_revision",
    label: "Revision",
    topicLabel: "Revision",
    keywords: ["revision", "revised initiative"],
    surfaces: ["revision"],
    purpose: "Produce the revised Initiative text that will ground Petition and later decisions.",
    input: "Selected Improvement Proposals and prior Initiative wording.",
    output: "Published Revision — the working public text for subsequent stages.",
    authorRole: "Integrates accepted improvements; publishes the Revision they stand behind.",
    participantRole: "Read the Revision that later Petition and Decision stages will reference.",
    assistantRole: "Help keep wording clear and neutral; never silently rewrite published history.",
    publicationMeaning: "The Revision becomes the reference text for Petition and Decision work.",
    nextStage: "Petition",
    relatedModuleIds: ["lifecycle_overview", "lifecycle_proposal"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_petition",
    label: "Petition",
    topicLabel: "Petition",
    keywords: ["petition", "signature", "endorsement", "petition statistics"],
    surfaces: ["petition"],
    purpose: "Gather public expressions of support for the revised civic request.",
    input: "Published Revision and clear petition request text.",
    output: "Petition record with signatures and public participation statistics.",
    authorRole: "Publishes a clear, evidence-aware request; does not coerce signatures.",
    participantRole: "May sign or decline; statistics reflect platform participation, not government authority.",
    assistantRole: "Help clarify the request and unsupported claims; never forge signatures.",
    publicationMeaning:
      "Petition statistics represent public participation on the Humanity Union platform. They are indicators of civic interest and support, not an official governmental or legally binding vote.",
    nextStage: "Decision Session",
    relatedModuleIds: ["participation_representative", "lifecycle_overview"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_decision_session",
    label: "Decision Session",
    topicLabel: "Decision Session",
    keywords: ["decision session", "options", "risks", "decision preparation"],
    surfaces: ["decision_session"],
    purpose: "Prepare options, risks, and decision framing before Collective Decision.",
    input: "Revision, Petition context, Analysis themes.",
    output: "Published Decision Session materials for participants to review.",
    authorRole: "Frames options and risks without fabricating certainty.",
    participantRole: "Review options and consequences before voting stages.",
    assistantRole: "Help compare options neutrally; do not tell people how to vote.",
    publicationMeaning: "Decision Session materials become the public preparation record.",
    nextStage: "Collective Decision",
    relatedModuleIds: ["lifecycle_overview", "lifecycle_collective_decision"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_collective_decision",
    label: "Collective Decision",
    topicLabel: "Collective Decision",
    keywords: [
      "collective decision",
      "vote",
      "voting",
      "decision result",
      "what was decided",
    ],
    surfaces: ["collective_decision"],
    purpose: "Record the Collective Decision — what the community decided on the Initiative path.",
    input: "Decision Session materials and eligible Participant votes under platform rules.",
    output: "Transparent Collective Decision results defining WHAT was decided.",
    authorRole: "Hosts the decision process within platform rules; does not rewrite results.",
    participantRole: "Eligible Participants may vote; results are transparent according to stage rules.",
    assistantRole: "Explain process and neutrality; never cast or change votes.",
    publicationMeaning: "The Collective Decision defines WHAT should be pursued next — not WHO must implement it.",
    nextStage: "Implementation Commitments",
    relatedModuleIds: ["lifecycle_overview", "commitments", "participation_representative"],
  }),
  {
    moduleId: "commitments",
    category: "commitments_tracking",
    label: "Implementation Commitments",
    topicLabel: "Implementation Commitments",
    keywords: [
      "commitment",
      "commitments",
      "implementation commitments",
      "responsibility",
      "accept commitment",
      "decline commitment",
      "who will",
    ],
    surfaces: ["commitment", "collective_decision", "tracking"],
    relatedModuleIds: ["tracking", "lifecycle_collective_decision"],
    content: [
      "According to the current Initiative Lifecycle — Implementation Commitments:",
      "Collective Decision defines WHAT. Implementation Commitments define WHO voluntarily accepts responsibility.",
      "Purpose: translate a decision into concrete, voluntary responsibilities (deliverable, resources, timing).",
      "Author role: may propose responsibility assignments; cannot force acceptance.",
      "Participant role: accept or decline proposed Commitments; no forced responsibility.",
      "AI Assistant role: help clarify deliverables and feasibility without judging personal worth; never accept for someone.",
      "Publication meaning: accepted Commitments become public responsibility records.",
      "Next stage: Implementation Tracking.",
    ].join("\n"),
  },
  {
    moduleId: "tracking",
    category: "commitments_tracking",
    label: "Implementation Tracking",
    topicLabel: "Implementation Tracking",
    keywords: [
      "tracking",
      "implementation tracking",
      "progress",
      "blocker",
      "how implementation",
    ],
    surfaces: ["tracking", "commitment", "public_impact"],
    relatedModuleIds: ["commitments", "lifecycle_public_impact"],
    content: [
      "According to the current Initiative Lifecycle — Implementation Tracking:",
      "Implementation Tracking shows HOW implementation is progressing against accepted Commitments.",
      "Purpose: record progress, evidence, and blockers over time.",
      "Author and committed Participants update Tracking with evidence-aware status — not promotional claims.",
      "AI Assistant role: help describe progress clearly and neutrally; never invent completed work.",
      "Publication meaning: Tracking becomes the evidence base for Public Impact.",
      "Next stage: Official Responses (when applicable), then Public Impact.",
    ].join("\n"),
  },
  stageKnowledge({
    moduleId: "lifecycle_official_response",
    label: "Official Responses",
    topicLabel: "Official Responses",
    keywords: ["official response", "official responses", "institution response"],
    surfaces: ["official_response"],
    purpose: "Record responses from relevant institutions or official bodies when they engage.",
    input: "Published Initiative path, decision, and delivery context.",
    output: "Published Official Response records linked to the Initiative.",
    authorRole: "May facilitate accurate presentation; must not fabricate institutional replies.",
    participantRole: "Read official responses as part of the public record.",
    assistantRole: "Help clarify what an Official Response is; never invent institutional statements.",
    publicationMeaning: "Official Responses become part of the public accountability record.",
    nextStage: "Public Impact",
    relatedModuleIds: ["lifecycle_overview", "tracking"],
  }),
  stageKnowledge({
    moduleId: "lifecycle_public_impact",
    label: "Public Impact",
    topicLabel: "Public Impact",
    keywords: ["public impact", "outcomes", "impact summary"],
    surfaces: ["public_impact"],
    purpose: "Summarize delivered outcomes and remaining work using Tracking evidence.",
    input: "Implementation Tracking evidence and related public records.",
    output: "Neutral Public Impact summary — outcomes with evidence vs remaining work.",
    authorRole: "Publishes a non-promotional impact summary grounded in evidence.",
    participantRole: "Assess claims against cited Tracking evidence.",
    assistantRole: "Help strengthen evidence links; popularity is not proof of impact.",
    publicationMeaning: "Public Impact becomes the public outcomes record before Archive.",
    nextStage: "Civic Archive",
    relatedModuleIds: ["tracking", "civic_archive"],
  }),
  stageKnowledge({
    moduleId: "civic_archive",
    label: "Civic Archive",
    topicLabel: "Civic Archive",
    keywords: ["civic archive", "archive", "lessons", "historical summary"],
    surfaces: ["archive"],
    purpose: "Preserve lessons, knowledge contribution, and historical summary of completed Initiative work.",
    input: "Prior published Lifecycle records and impact evidence.",
    output: "Archived knowledge contribution others can discover and learn from.",
    authorRole: "Contributes an accurate Archive summary without rewriting earlier published facts.",
    participantRole: "Consult Archive as learning material for future Initiatives.",
    assistantRole: "Help summarize lessons without inventing Archive contents that were never published.",
    publicationMeaning: "Archive preserves public learning; it is not a place to hide failures or invent success.",
    nextStage: "Lifecycle complete for this Initiative path (knowledge remains discoverable).",
    relatedModuleIds: ["lifecycle_overview", "lifecycle_public_impact"],
  }),
  {
    moduleId: "participation_representative",
    category: "participation",
    label: "Representative participation",
    topicLabel: "Representative participation",
    keywords: [
      "support",
      "do not support",
      "signature",
      "signatures",
      "visitors",
      "representative statistics",
      "formal participation",
      "non-binding",
      "binding vote",
    ],
    surfaces: ["petition", "initiative", "collective_decision", "initiatives"],
    relatedModuleIds: ["lifecycle_petition", "participant_member"],
    content: [
      "Representative participation on Humanity Union includes Support / Do Not Support signals,",
      "Petition signatures, and related public statistics involving Participants, Members, and Visitors where allowed.",
      "These are indicators of civic interest and platform participation.",
      "Formal Collective Decision voting is a distinct Lifecycle action with its own eligibility rules —",
      "do not conflate Petition signatures or Support signals with Collective Decision votes.",
      "Canonical Petition principle: Petition statistics represent public participation on the Humanity Union platform.",
      "They are indicators of civic interest and support, not an official governmental or legally binding vote.",
    ].join(" "),
  },
];
