import type { PlatformKnowledgeModule } from "../types.js";

export const NOTIFICATIONS_PRIVACY_SAFETY_MODULES: readonly PlatformKnowledgeModule[] = [
  {
    moduleId: "notifications",
    category: "notifications",
    label: "Notifications",
    topicLabel: "Notifications",
    keywords: [
      "notification",
      "notifications",
      "notification center",
      "alert",
      "invitation",
      "lifecycle event",
    ],
    surfaces: ["notifications", "workspace", "preferences"],
    relatedModuleIds: ["reminders", "messages"],
    content: [
      "Notifications are durable platform and Initiative event alerts — for example Lifecycle publications,",
      "collaboration invitations, and participation events.",
      "Notifications are not private chat content and do not contain full message transcripts.",
      "In the Notification Center, distinguish: Notifications (events), Messages (unread communication links to Workspace Messages),",
      "Reminders (next steps / deadlines / priority opportunities), and Archive (completed Notifications and Reminders).",
      "Messages remain in chat history; they are not stored as Notification Archive items.",
    ].join(" "),
  },
  {
    moduleId: "reminders",
    category: "reminders",
    label: "Reminders",
    topicLabel: "Reminders",
    keywords: ["reminder", "reminders", "deadline", "next step", "session reminder"],
    surfaces: ["notifications", "workspace"],
    relatedModuleIds: ["notifications", "collaboration"],
    content: [
      "Reminders are time-aware or priority-related prompts for next steps — for example Collaboration Sessions",
      "or pending civic actions the Participant may still need to complete.",
      "Reminders never vote, publish, send messages, or accept Commitments on anyone’s behalf.",
      "Completed Reminders may move to Archive alongside completed Notifications.",
    ].join(" "),
  },
  {
    moduleId: "privacy",
    category: "privacy",
    label: "Privacy",
    topicLabel: "Privacy",
    keywords: [
      "privacy",
      "visibility",
      "public profile",
      "skills visibility",
      "professional links",
      "organization visibility",
      "location visibility",
      "participation area visibility",
      "messaging policy",
      "private content",
    ],
    surfaces: ["profile", "preferences", "messages"],
    relatedModuleIds: ["profile", "preferences", "messages", "safety"],
    content: [
      "Privacy controls govern what others see: public profile visibility, skills, professional links,",
      "organization, location, and Participation Area presentation.",
      "Messaging policy covers who may start Direct Messages and how private conversations remain private.",
      "Private vs public content boundaries: Author Workspace drafts, private messages, credentials, and personal documents",
      "are not public civic records and are never sent to AI automatically.",
      "Knowing that a privacy policy exists does not authorize exposing private field values.",
    ].join(" "),
  },
  {
    moduleId: "media",
    category: "media",
    label: "Media",
    topicLabel: "Media",
    keywords: ["media", "cover", "image", "upload", "verification", "trusted media"],
    surfaces: ["initiative", "initiatives", "archive"],
    relatedModuleIds: ["safety", "initiatives"],
    content: [
      "Initiatives and related surfaces may include cover media and other media assets.",
      "Some media may require verification or moderation before it is trusted for public presentation.",
      "The Assistant may explain that media can require verification; it must not describe internal moderation algorithms",
      "or ways to bypass Safety checks.",
    ].join(" "),
  },
  {
    moduleId: "safety",
    category: "safety",
    label: "Safety",
    topicLabel: "Safety",
    keywords: [
      "safety",
      "rejected",
      "moderation",
      "authentication",
      "prompt injection",
      "validation",
    ],
    surfaces: "all",
    relatedModuleIds: ["privacy", "assistant_capabilities"],
    content: [
      "Safety validation runs before content may enter Stage Intelligence or external AI prompts.",
      "Content or media can be rejected when it violates Safety rules; rejected prompts never reach the provider.",
      "Private data is not sent to AI automatically. Some actions require authentication so personal context stays bound to identity.",
      "Explain why rejection, verification, or sign-in may be required — without revealing internal security implementation details that weaken protection.",
    ].join(" "),
  },
  {
    moduleId: "assistant_capabilities",
    category: "assistant_capabilities",
    label: "Assistant capabilities",
    topicLabel: "AI Assistant role",
    keywords: [
      "assistant",
      "ai",
      "capabilities",
      "advisory",
      "humanity union assistant",
      "what can you do",
    ],
    surfaces: "all",
    content: [
      "The Humanity Union Assistant is advisory only.",
      "It helps Participants understand the platform, Lifecycle stages, Workspace tools, and evidence-aware civic reasoning.",
      "It never publishes, votes, sends messages, edits stored drafts, accepts Commitments, or mutates civic records automatically.",
      "Suggestions require Participant review. Session history is temporary for the modal session and is not stored as Direct Messages.",
      "When platform knowledge does not support an answer, the Assistant must admit uncertainty rather than invent features.",
    ].join(" "),
  },
];
