import type { TrustedMediaResource } from "@hu/types";

export const TRUSTED_MEDIA_RESOURCES: readonly TrustedMediaResource[] = [
  {
    id: "reuters",
    name: "Reuters",
    logoLabel: "R",
    logoUrl: "/images/media/reuters.webp",
    country: "International",
    categoryId: "international-wire-service",
    explanation:
      "Independent international news agency with global editorial standards and correction policies.",
    websiteUrl: "https://www.reuters.com/",
    sortOrder: 1,
  },
  {
    id: "associated-press",
    name: "Associated Press",
    logoLabel: "AP",
    logoUrl: "/images/media/ap.webp",
    country: "United States",
    categoryId: "international-wire-service",
    explanation:
      "Cooperative news agency providing factual reporting with transparent standards of accuracy.",
    websiteUrl: "https://apnews.com/",
    sortOrder: 2,
  },
  {
    id: "afp",
    name: "AFP",
    logoLabel: "AFP",
    logoUrl: "/images/media/afp.webp",
    country: "France",
    categoryId: "international-wire-service",
    explanation:
      "International news agency with editorial independence and multilingual global coverage.",
    websiteUrl: "https://www.afp.com/",
    sortOrder: 3,
  },
  {
    id: "al-jazeera",
    name: "Al Jazeera",
    logoLabel: "AJ",
    logoUrl: "/images/media/aljazeera.webp",
    country: "International",
    categoryId: "international-wire-service",
    explanation:
      "International news organization with multilingual coverage and published editorial standards.",
    websiteUrl: "https://www.aljazeera.com/",
    sortOrder: 4,
  },
  {
    id: "bbc",
    name: "BBC",
    logoLabel: "BBC",
    logoUrl: "/images/media/bbc.webp",
    country: "United Kingdom",
    categoryId: "public-broadcaster",
    explanation:
      "Public service broadcaster with editorial guidelines and a published corrections policy.",
    websiteUrl: "https://www.bbc.com/",
    sortOrder: 5,
  },
  {
    id: "npr",
    name: "NPR",
    logoLabel: "NPR",
    logoUrl: "/images/media/npr.webp",
    country: "United States",
    categoryId: "public-broadcaster",
    explanation:
      "Nonprofit public media organization focused on in-depth reporting and public accountability.",
    websiteUrl: "https://www.npr.org/",
    sortOrder: 6,
  },
  {
    id: "pbs",
    name: "PBS",
    logoLabel: "PBS",
    logoUrl: "/images/media/pbs.webp",
    country: "United States",
    categoryId: "public-broadcaster",
    explanation:
      "Public broadcasting network providing documentary and investigative journalism programs.",
    websiteUrl: "https://www.pbs.org/",
    sortOrder: 7,
  },
  {
    id: "deutsche-welle",
    name: "Deutsche Welle",
    logoLabel: "DW",
    logoUrl: "/images/media/dw.webp",
    country: "Germany",
    countryCode: "DE",
    categoryId: "public-broadcaster",
    explanation:
      "International public broadcaster providing multilingual news and documentary coverage.",
    websiteUrl: "https://www.dw.com/",
    sortOrder: 8,
  },
  {
    id: "propublica",
    name: "ProPublica",
    logoLabel: "PP",
    country: "United States",
    categoryId: "independent-investigative",
    explanation:
      "Independent nonprofit newsroom specializing in investigative journalism with published methodology.",
    websiteUrl: "https://www.propublica.org/",
    sortOrder: 9,
  },
  {
    id: "occrp",
    name: "OCCRP",
    logoLabel: "OC",
    country: "International",
    categoryId: "independent-investigative",
    explanation:
      "Consortium of investigative centers focused on corruption and organized crime with cross-border reporting.",
    websiteUrl: "https://www.occrp.org/",
    sortOrder: 10,
  },
  {
    id: "the-guardian",
    name: "The Guardian",
    logoLabel: "G",
    logoUrl: "/images/media/guardian.webp",
    country: "United Kingdom",
    categoryId: "independent-investigative",
    explanation:
      "Independent news organization with published editorial standards and corrections policy.",
    websiteUrl: "https://www.theguardian.com/",
    sortOrder: 11,
  },
  {
    id: "new-york-times",
    name: "The New York Times",
    logoLabel: "NYT",
    logoUrl: "/images/media/nytimes.webp",
    country: "United States",
    categoryId: "independent-investigative",
    explanation:
      "National newspaper with published standards for accuracy, corrections, and editorial independence.",
    websiteUrl: "https://www.nytimes.com/",
    sortOrder: 12,
  },
  {
    id: "washington-post",
    name: "The Washington Post",
    logoLabel: "WP",
    logoUrl: "/images/media/wpost.webp",
    country: "United States",
    categoryId: "independent-investigative",
    explanation:
      "National newspaper covering public policy and civic affairs with published editorial standards.",
    websiteUrl: "https://www.washingtonpost.com/",
    sortOrder: 13,
  },
  {
    id: "cbc",
    name: "CBC",
    logoLabel: "CBC",
    logoUrl: "/images/media/canada/cbc.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "regional-public-media",
    explanation:
      "Canadian public broadcaster with journalistic standards and regional news coverage.",
    websiteUrl: "https://www.cbc.ca/",
    sortOrder: 14,
  },
  {
    id: "globe-and-mail",
    name: "The Globe and Mail",
    logoLabel: "GM",
    logoUrl: "/images/media/canada/globe-mail.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "regional-public-media",
    explanation:
      "Canadian national newspaper covering civic affairs, policy, and regional public interest reporting.",
    websiteUrl: "https://www.theglobeandmail.com/",
    sortOrder: 15,
  },
  {
    id: "global-news-canada",
    name: "Global News",
    logoLabel: "GN",
    logoUrl: "/images/media/canada/global-news.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "regional-public-media",
    explanation:
      "Canadian national news network covering civic affairs and regional public interest reporting.",
    websiteUrl: "https://globalnews.ca/",
    sortOrder: 16,
  },
  {
    id: "la-presse-canada",
    name: "La Presse",
    logoLabel: "LP",
    logoUrl: "/images/media/canada/la-presse.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "regional-public-media",
    explanation:
      "Canadian French-language news organization covering civic affairs and public policy.",
    websiteUrl: "https://www.lapresse.ca/",
    sortOrder: 17,
  },
  {
    id: "canadian-press",
    name: "The Canadian Press",
    logoLabel: "CP",
    logoUrl: "/images/media/canada/ca-press.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "international-wire-service",
    explanation:
      "Canadian news cooperative providing national and regional reporting with editorial standards.",
    websiteUrl: "https://www.thecanadianpress.com/",
    sortOrder: 18,
  },
  {
    id: "ctv-news-canada",
    name: "CTV News",
    logoLabel: "CTV",
    logoUrl: "/images/media/canada/ctv.webp",
    country: "Canada",
    countryCode: "CA",
    categoryId: "regional-public-media",
    explanation: "Canadian television news network covering national and regional civic affairs.",
    websiteUrl: "https://www.ctvnews.ca/",
    sortOrder: 19,
  },
  {
    id: "tagesschau",
    name: "Tagesschau",
    logoLabel: "TS",
    logoUrl: "/images/media/germany/tagesschau.webp",
    country: "Germany",
    countryCode: "DE",
    categoryId: "public-broadcaster",
    explanation:
      "German public news service providing national and regional civic reporting with editorial standards.",
    websiteUrl: "https://www.tagesschau.de/",
    sortOrder: 20,
  },
  {
    id: "der-spiegel",
    name: "Spiegel",
    logoLabel: "SP",
    logoUrl: "/images/media/germany/spiegel.webp",
    country: "Germany",
    countryCode: "DE",
    categoryId: "independent-investigative",
    explanation:
      "German news magazine covering public policy, civic affairs, and investigative reporting.",
    websiteUrl: "https://www.spiegel.de/",
    sortOrder: 21,
  },
  {
    id: "suspilne",
    name: "Suspilne",
    logoLabel: "SU",
    logoUrl: "/images/media/ukraine/hromadske.webp",
    country: "Ukraine",
    countryCode: "UA",
    categoryId: "public-broadcaster",
    explanation:
      "Ukrainian public broadcaster providing national news coverage with published editorial standards.",
    websiteUrl: "https://suspilne.media/",
    sortOrder: 22,
  },
  {
    id: "ukrinform-ukraine",
    name: "Ukrinform",
    logoLabel: "UI",
    logoUrl: "/images/media/ukraine/ukrinform.webp",
    country: "Ukraine",
    countryCode: "UA",
    categoryId: "regional-public-media",
    explanation:
      "Ukrainian national news agency providing civic and public interest reporting.",
    websiteUrl: "https://www.ukrinform.net/",
    sortOrder: 23,
  },
  {
    id: "european-pravda",
    name: "European Pravda",
    logoLabel: "EP",
    logoUrl: "/images/media/ukraine/ukraine-pravda.webp",
    country: "Ukraine",
    countryCode: "UA",
    categoryId: "independent-investigative",
    explanation:
      "Ukrainian English-language outlet covering European integration, civic reform, and public policy.",
    websiteUrl: "https://www.eurointegration.com.ua/en",
    sortOrder: 24,
  },
  {
    id: "kyiv-independent",
    name: "Kyiv Independent",
    logoLabel: "KI",
    logoUrl: "/images/media/ukraine/liganet.webp",
    country: "Ukraine",
    countryCode: "UA",
    categoryId: "independent-investigative",
    explanation:
      "Independent English-language newsroom reporting on civic life, policy, and public accountability in Ukraine.",
    websiteUrl: "https://kyivindependent.com/",
    sortOrder: 25,
  },
  {
    id: "le-monde",
    name: "Le Monde",
    logoLabel: "LM",
    logoUrl: "/images/media/le-monde.webp",
    country: "France",
    categoryId: "regional-public-media",
    explanation:
      "French national newspaper with published editorial standards and civic affairs coverage.",
    websiteUrl: "https://www.lemonde.fr/",
    sortOrder: 26,
  },
  {
    id: "abc-australia",
    name: "ABC Australia",
    logoLabel: "ABC",
    country: "Australia",
    categoryId: "regional-public-media",
    explanation:
      "Australian public broadcaster providing national and regional news with editorial accountability.",
    websiteUrl: "https://www.abc.net.au/",
    sortOrder: 27,
  },
  {
    id: "nature",
    name: "Nature",
    logoLabel: "Nat",
    country: "International",
    categoryId: "scientific-publisher",
    explanation:
      "Peer-reviewed scientific journal publishing research with rigorous editorial and review processes.",
    websiteUrl: "https://www.nature.com/",
    sortOrder: 28,
  },
  {
    id: "science-magazine",
    name: "Science",
    logoLabel: "Sci",
    country: "International",
    categoryId: "scientific-publisher",
    explanation:
      "Peer-reviewed journal of the American Association for the Advancement of Science.",
    websiteUrl: "https://www.science.org/",
    sortOrder: 29,
  },
  {
    id: "jstor",
    name: "JSTOR",
    logoLabel: "JS",
    country: "International",
    categoryId: "academic-resource",
    explanation:
      "Digital library of academic journals, books, and primary sources for evidence-based research.",
    websiteUrl: "https://www.jstor.org/",
    sortOrder: 30,
  },
  {
    id: "britannica",
    name: "Britannica",
    logoLabel: "BE",
    country: "International",
    categoryId: "academic-resource",
    explanation: "Encyclopedic reference resource with editorial review and source citations.",
    websiteUrl: "https://www.britannica.com/",
    sortOrder: 31,
  },
] as const;
