import { article } from "../article-factory.js";

function explanation(
  slug: string,
  title: string,
  purpose: string,
  overview: string,
  diagramId: string,
  body: string,
  keyConcepts: string[],
  sortOrder: number,
  extra: Partial<Parameters<typeof article>[0]> = {},
) {
  return article({
    slug,
    categoryId: "explanations",
    title,
    purpose,
    overview,
    diagramId,
    explanation: [{ id: "main", heading: "Explanation", body }],
    keyConcepts,
    relatedConceptSlugs: extra.relatedConceptSlugs ?? ["capability02-civic-pipeline"],
    relatedGuideSlugs: extra.relatedGuideSlugs ?? [],
    relatedWorkspaceSection: extra.relatedWorkspaceSection,
    relatedPublicPageHrefs: extra.relatedPublicPageHrefs ?? [],
    readingTimeMinutes: extra.readingTimeMinutes ?? 3,
    searchTerms: extra.searchTerms ?? [slug.replace(/-/g, " "), title.toLowerCase()],
    assistantTags: extra.assistantTags ?? [slug],
    sortOrder,
    ...extra,
  });
}

export const EXPLANATIONS_ARTICLES = [
  explanation(
    "what-is-an-initiative",
    "What is an Initiative?",
    "What is a civic initiative on Humanity Union?",
    "An initiative is the starting civic record. It states a title, description, and participation context for collective work.",
    "initiative-lifecycle",
    "Initiatives begin in draft while stewards refine language and scope. Publishing makes the initiative visible in Public Experience. The initiative anchors all later analyses, proposals, and decisions.",
    ["Steward", "Lifecycle", "Participation area"],
    1,
    {
      relatedGuideSlugs: ["create-your-first-initiative"],
      relatedWorkspaceSection: "Initiatives",
      relatedPublicPageHrefs: [{ title: "Initiatives", href: "/initiatives" }],
      assistantTags: ["initiative", "explain_current_section"],
    },
  ),
  explanation(
    "collaborative-analysis",
    "Collaborative Analysis",
    "What is collaborative analysis?",
    "Collaborative analysis lets participants examine an initiative from multiple perspectives before proposing changes.",
    "process-flow",
    "An analysis record captures structured review of an initiative. Published analyses become part of the public civic trail and may inform improvement proposals.",
    ["Analysis", "Evidence", "Collaboration"],
    2,
    { assistantTags: ["analysis", "structure_analysis", "explain_current_section"] },
  ),
  explanation(
    "improvement-proposal",
    "Improvement Proposal",
    "What is an improvement proposal?",
    "An improvement proposal suggests a specific change to an initiative section based on analysis or participant input.",
    "process-flow",
    "Proposals target a defined section of the initiative. They move through review before revision or decision stages. Draft proposals remain workspace-only.",
    ["Proposal", "Target section", "Revision"],
    3,
    {
      relatedGuideSlugs: ["write-better-proposals"],
      assistantTags: ["proposal", "structure_proposal"],
    },
  ),
  explanation(
    "decision-session",
    "Decision Session",
    "What is a decision session?",
    "A decision session prepares participants for a collective decision by publishing the question, options, and eligibility rules.",
    "process-flow",
    "Decision sessions frame what will be decided and who may participate. They precede collective decision opening and voting.",
    ["Session", "Eligibility", "Options"],
    4,
    { assistantTags: ["decision_session", "explain_decision_session"] },
  ),
  explanation(
    "collective-decision",
    "Collective Decision",
    "What is a collective decision?",
    "A collective decision records a governed vote or consensus process on a published question.",
    "process-flow",
    "Participants cast votes according to participation area rules. Results are transparent and become part of the public civic record.",
    ["Vote", "Outcome", "Transparency"],
    5,
    {
      relatedGuideSlugs: ["understand-decision-results"],
      assistantTags: ["collective_decision", "explain_decision_result"],
    },
  ),
  explanation(
    "implementation-commitment",
    "Implementation Commitment",
    "What is an implementation commitment?",
    "An implementation commitment declares how a community will act on a collective decision.",
    "process-flow",
    "Commitments translate decision outcomes into declared capacity and readiness. They are published civic records, not automatic execution orders.",
    ["Commitment", "Capacity", "Readiness"],
    6,
    { assistantTags: ["implementation_commitment"] },
  ),
  explanation(
    "implementation-tracking",
    "Implementation Tracking",
    "What is implementation tracking?",
    "Implementation tracking documents progress against a published commitment over time.",
    "process-flow",
    "Tracking records milestones, updates, and status changes. It helps participants and observers see whether declared work is proceeding.",
    ["Tracking", "Milestone", "Progress"],
    7,
    {
      relatedGuideSlugs: ["track-implementation"],
      assistantTags: ["implementation_tracking", "structure_implementation_update"],
    },
  ),
  explanation(
    "public-impact",
    "Public Impact",
    "What is public impact?",
    "Public impact summarizes observed outcomes linked to civic work and evidence.",
    "process-flow",
    "Impact records connect results to initiatives and tracking. They are published for public understanding, not as official legal findings.",
    ["Impact", "Evidence", "Outcome"],
    8,
    {
      relatedGuideSlugs: ["prepare-public-impact"],
      assistantTags: ["public_impact", "clarify_public_impact"],
    },
  ),
  explanation(
    "public-civic-archive",
    "Public Civic Archive",
    "What is the Public Civic Archive?",
    "The archive preserves completed civic work as durable public memory.",
    "process-flow",
    "Archive records capture lessons, references, and final states. They support long-term research without altering original records.",
    ["Archive", "Civic memory", "Lessons learned"],
    9,
    {
      relatedGuideSlugs: ["archive-experience"],
      assistantTags: ["civic_archive", "prepare_archive_lessons"],
      relatedPublicPageHrefs: [{ title: "Civic Archive", href: "/civic-archive" }],
    },
  ),
  explanation(
    "civic-action-package",
    "Civic Action Package",
    "What is a Civic Action Package (CAP)?",
    "A Civic Action Package bundles a collective decision outcome for delivery to institutions or recipients.",
    "civic-pipeline",
    "CAPs formalize what is being communicated externally. They link back to decisions and initiatives for full context.",
    ["CAP", "Delivery", "Institution"],
    10,
    {
      assistantTags: ["civic_action_package", "prepare_cap_summary"],
      relatedConceptSlugs: ["how-delivery-works", "cap-glossary"],
    },
  ),
  explanation(
    "official-response",
    "Official Response",
    "What is an Official Response?",
    "An official response records how an institution or authorized party replied to civic delivery.",
    "process-flow",
    "Responses are published with verification metadata. They do not imply platform endorsement of institutional positions.",
    ["Response", "Verification", "Publication"],
    11,
    { assistantTags: ["official_response", "summarize_official_response"] },
  ),
  explanation(
    "civic-accountability",
    "Civic Accountability",
    "What is Civic Accountability?",
    "Civic accountability tracks follow-up obligations after official responses or commitments.",
    "process-flow",
    "Accountability records document events and status over time. They support transparency without assigning legal liability.",
    ["Accountability", "Follow-up", "Events"],
    12,
    { assistantTags: ["civic_accountability", "prepare_accountability_event"] },
  ),
  explanation(
    "capability02-civic-pipeline",
    "Capability 02 Civic Pipeline",
    "What is the Capability 02 civic pipeline?",
    "Capability 02 is the governed sequence of civic records from initiative through archive.",
    "civic-pipeline",
    "Each stage produces a distinct record type. Stages must generally complete in order; the integration layer links related records without duplicating logic.",
    ["Pipeline", "Integration layer", "Stage"],
    13,
    {
      relatedConceptSlugs: ["what-is-an-initiative", "public-civic-archive"],
      assistantTags: ["pipeline", "explain_pipeline_status", "review_related_records"],
    },
  ),
  explanation(
    "participation-areas",
    "Participation Areas",
    "What is a participation area?",
    "A participation area declares where a participant may engage in geographically scoped civic processes.",
    "participation-area",
    "Areas may be world, country, region, or community scoped. They affect eligibility for some collective decisions.",
    ["Participation", "Eligibility", "Geography"],
    14,
    {
      relatedWorkspaceSection: "Participation Area",
      assistantTags: ["participation_area"],
    },
  ),
  explanation(
    "workspace",
    "Workspace",
    "What is the participant workspace?",
    "The workspace is the authenticated home for civic work, profile, and notifications.",
    "workspace-overview",
    "Workspace Home summarizes active work, responsibilities, and readiness. Individual sections host initiative tools and member settings.",
    ["Workspace Home", "Active work", "Profile"],
    15,
    {
      relatedWorkspaceSection: "Workspace Home",
      relatedPublicPageHrefs: [{ title: "Workspace", href: "/workspace" }],
      assistantTags: ["workspace", "explain_current_section"],
    },
  ),
  explanation(
    "global-search",
    "Global Search",
    "What is Global Search?",
    "Global Search finds published civic records and Knowledge Center articles using deterministic matching.",
    "platform-overview",
    "Search ranks by explicit field matches — title, summary, location, and type. It does not use popularity or AI ranking.",
    ["Search", "Facets", "Public records"],
    16,
    {
      relatedPublicPageHrefs: [{ title: "Search", href: "/search" }],
      assistantTags: ["search"],
    },
  ),
  explanation(
    "notifications",
    "Notifications",
    "How do civic notifications work?",
    "Notifications inform participants about relevant civic events in their workspace.",
    "workspace-overview",
    "Event types are defined in the civic notification registry. Notifications support awareness; they do not require immediate action.",
    ["Notification", "Event", "Registry"],
    17,
    {
      relatedWorkspaceSection: "Notifications",
      relatedPublicPageHrefs: [{ title: "Notifications", href: "/notifications" }],
      assistantTags: ["notifications"],
    },
  ),
  explanation(
    "ai-assistant",
    "AI Assistant",
    "What is the Workspace Civic Assistant?",
    "The assistant provides advisory help inside the workspace. It references Knowledge Center articles instead of inventing explanations.",
    "workspace-overview",
    "Assistant responses are advisory only. Participants remain responsible for all civic actions. The assistant may suggest drafts but never executes mutations.",
    ["Assistant", "Advisory", "Knowledge references"],
    18,
    {
      relatedConceptSlugs: ["core-principles"],
      assistantTags: ["assistant", "explain_current_section", "identify_next_step"],
    },
  ),
];
