import { article } from "../article-factory.js";

export const FAQ_ARTICLES = [
  article({
    slug: "faq-is-humanity-union-a-government",
    categoryId: "faq",
    title: "Is Humanity Union a government?",
    purpose: "Is Humanity Union a government body?",
    overview:
      "No. Humanity Union is civic technology infrastructure. It does not exercise governmental authority.",
    diagramId: "platform-overview",
    explanation: [
      {
        id: "answer",
        heading: "Answer",
        body: "Institutions retain their authority. The platform documents civic participation.",
      },
    ],
    keyConcepts: ["Platform", "Institution"],
    relatedConceptSlugs: ["what-is-humanity-union"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 1,
    searchTerms: ["government", "faq"],
    assistantTags: ["platform"],
    sortOrder: 1,
  }),
  article({
    slug: "faq-do-i-need-an-account",
    categoryId: "faq",
    title: "Do I need an account to read public records?",
    purpose: "Do I need an account to browse public content?",
    overview: "No. Public Experience and Knowledge Center are readable without signing in.",
    diagramId: "platform-overview",
    explanation: [
      {
        id: "answer",
        heading: "Answer",
        body: "An account is required for workspace participation — creating initiatives, voting, and notifications.",
      },
    ],
    keyConcepts: ["Public", "Account"],
    relatedConceptSlugs: ["platform-overview"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 1,
    searchTerms: ["account", "login", "faq"],
    assistantTags: ["platform"],
    sortOrder: 2,
  }),
  article({
    slug: "faq-what-is-closed-beta",
    categoryId: "faq",
    title: "What is closed beta?",
    purpose: "What does closed beta mean?",
    overview:
      "Closed beta means access is invite-only while the platform stabilizes with early participants.",
    diagramId: "platform-overview",
    explanation: [
      {
        id: "answer",
        heading: "Answer",
        body: "Some areas may remain unfinished. Feedback helps improve stability before wider release.",
      },
    ],
    keyConcepts: ["Beta", "Access"],
    relatedConceptSlugs: ["what-is-humanity-union"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [{ title: "Support", href: "/support" }],
    readingTimeMinutes: 1,
    searchTerms: ["beta", "invite", "faq"],
    assistantTags: ["platform"],
    sortOrder: 3,
  }),
  article({
    slug: "faq-does-assistant-decide",
    categoryId: "faq",
    title: "Does the assistant decide outcomes?",
    purpose: "Can the AI assistant make civic decisions for me?",
    overview: "No. The assistant is advisory. Participants remain responsible for all actions.",
    diagramId: "workspace-overview",
    explanation: [
      {
        id: "answer",
        heading: "Answer",
        body: "The assistant references Knowledge Center articles and may suggest draft language. It cannot vote, publish, or verify on your behalf.",
      },
    ],
    keyConcepts: ["Assistant", "Advisory"],
    relatedConceptSlugs: ["ai-assistant"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 1,
    searchTerms: ["assistant", "ai", "faq"],
    assistantTags: ["assistant"],
    sortOrder: 4,
  }),
  article({
    slug: "faq-where-is-source-of-truth",
    categoryId: "faq",
    title: "Where is the source of truth?",
    purpose: "Which records are authoritative?",
    overview:
      "Governed civic records in the workspace data store are authoritative. Public pages and Knowledge are reference layers.",
    diagramId: "reference-architecture",
    explanation: [
      {
        id: "answer",
        heading: "Answer",
        body: "If a public projection differs from the source record, the source record governs.",
      },
    ],
    keyConcepts: ["Source of truth", "Projection"],
    relatedConceptSlugs: ["reference-only-architecture"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 1,
    searchTerms: ["source", "truth", "faq"],
    assistantTags: ["principles"],
    sortOrder: 5,
  }),
];
