import { article } from "../article-factory.js";

export const GUIDES_ARTICLES = [
  article({
    slug: "create-your-first-initiative",
    categoryId: "guides",
    title: "Create your first initiative",
    purpose: "How do I create my first initiative?",
    overview:
      "Sign in, open Initiatives, and start a draft with a clear title and description tied to your participation area.",
    diagramId: "initiative-lifecycle",
    explanation: [
      {
        id: "step1",
        heading: "1. Open Initiatives",
        body: "From Workspace or the Initiatives page, choose to create a new draft.",
      },
      {
        id: "step2",
        heading: "2. Write clearly",
        body: "State the civic question, scope, and intended participation area.",
      },
      {
        id: "step3",
        heading: "3. Publish when ready",
        body: "Review draft content, then publish to make the initiative public.",
      },
    ],
    keyConcepts: ["Draft", "Publish", "Steward"],
    relatedConceptSlugs: ["what-is-an-initiative", "participation-areas"],
    relatedGuideSlugs: [],
    relatedWorkspaceSection: "Initiatives",
    relatedPublicPageHrefs: [{ title: "Initiatives", href: "/initiatives" }],
    readingTimeMinutes: 4,
    searchTerms: ["create", "first initiative", "tutorial"],
    assistantTags: ["initiative", "identify_next_step"],
    sortOrder: 1,
  }),
  article({
    slug: "prepare-good-evidence",
    categoryId: "guides",
    title: "Prepare good evidence",
    purpose: "How do I prepare strong evidence for civic work?",
    overview:
      "Use verifiable sources, clear citations, and proportionate claims. Link evidence to specific initiative sections.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "sources",
        heading: "Cite sources",
        body: "Prefer primary documents, official data, and attributable references.",
      },
      {
        id: "proportion",
        heading: "Stay proportionate",
        body: "Match evidence strength to the claim being made.",
      },
    ],
    keyConcepts: ["Evidence", "Citation", "Verification"],
    relatedConceptSlugs: ["collaborative-analysis", "public-impact"],
    relatedGuideSlugs: ["write-better-proposals"],
    relatedWorkspaceSection: "Collaborative Analysis",
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 4,
    searchTerms: ["evidence", "citation", "sources"],
    assistantTags: ["strengthen_evidence"],
    sortOrder: 2,
  }),
  article({
    slug: "write-better-proposals",
    categoryId: "guides",
    title: "Write better proposals",
    purpose: "How do I write effective improvement proposals?",
    overview:
      "Target one section, state the change, explain rationale, and reference supporting analysis.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "focus",
        heading: "One section at a time",
        body: "Proposals should be reviewable in isolation.",
      },
      {
        id: "rationale",
        heading: "Explain why",
        body: "Connect the proposal to analysis findings or participant feedback.",
      },
    ],
    keyConcepts: ["Proposal", "Section", "Rationale"],
    relatedConceptSlugs: ["improvement-proposal"],
    relatedGuideSlugs: ["prepare-good-evidence"],
    relatedWorkspaceSection: "Improvement Proposals",
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 4,
    searchTerms: ["proposal", "write", "improvement"],
    assistantTags: ["structure_proposal"],
    sortOrder: 3,
  }),
  article({
    slug: "understand-decision-results",
    categoryId: "guides",
    title: "Understand decision results",
    purpose: "How do I read collective decision results?",
    overview:
      "Review vote counts, participation confidence, and outcome type. Results describe the decision; they do not execute it.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "counts",
        heading: "Vote counts",
        body: "Transparent results show choices and cohort statistics where applicable.",
      },
      {
        id: "outcome",
        heading: "Outcome type",
        body: "Outcomes indicate whether the question passed, failed, or requires further process.",
      },
    ],
    keyConcepts: ["Results", "Outcome", "Transparency"],
    relatedConceptSlugs: ["collective-decision", "decision-session"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 4,
    searchTerms: ["decision", "results", "vote"],
    assistantTags: ["explain_decision_result"],
    sortOrder: 4,
  }),
  article({
    slug: "track-implementation",
    categoryId: "guides",
    title: "Track implementation",
    purpose: "How do I track implementation progress?",
    overview:
      "After a published commitment, open implementation tracking and log updates at meaningful milestones.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "commitment",
        heading: "Start from commitment",
        body: "Tracking links to a published implementation commitment.",
      },
      {
        id: "updates",
        heading: "Log updates",
        body: "Record progress honestly with dates and summaries.",
      },
    ],
    keyConcepts: ["Tracking", "Update", "Milestone"],
    relatedConceptSlugs: ["implementation-tracking", "implementation-commitment"],
    relatedGuideSlugs: [],
    relatedWorkspaceSection: "Implementation Tracking",
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 4,
    searchTerms: ["track", "implementation", "progress"],
    assistantTags: ["structure_implementation_update"],
    sortOrder: 5,
  }),
  article({
    slug: "prepare-public-impact",
    categoryId: "guides",
    title: "Prepare Public Impact",
    purpose: "How do I document public impact?",
    overview:
      "Summarize observed outcomes, attach evidence references, and publish when ready for public review.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "observe",
        heading: "Describe outcomes",
        body: "Focus on observable effects linked to the initiative.",
      },
      {
        id: "evidence",
        heading: "Attach evidence",
        body: "Reference supporting materials without overstating causation.",
      },
    ],
    keyConcepts: ["Impact", "Evidence", "Outcome"],
    relatedConceptSlugs: ["public-impact"],
    relatedGuideSlugs: ["prepare-good-evidence"],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 4,
    searchTerms: ["public impact", "outcome", "document"],
    assistantTags: ["clarify_public_impact"],
    sortOrder: 6,
  }),
  article({
    slug: "archive-experience",
    categoryId: "guides",
    title: "Archive experience",
    purpose: "How do I archive completed civic work?",
    overview:
      "When civic work concludes, create an archive record that references key decisions, deliveries, and lessons.",
    diagramId: "reference-architecture",
    explanation: [
      {
        id: "when",
        heading: "When to archive",
        body: "Archive when the initiative lifecycle is complete and public record is stable.",
      },
      {
        id: "lessons",
        heading: "Capture lessons",
        body: "Document what worked and what participants learned for future reference.",
      },
    ],
    keyConcepts: ["Archive", "Lessons", "References"],
    relatedConceptSlugs: ["public-civic-archive"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [{ title: "Civic Archive", href: "/civic-archive" }],
    readingTimeMinutes: 4,
    searchTerms: ["archive", "lessons", "complete"],
    assistantTags: ["prepare_archive_lessons"],
    sortOrder: 7,
  }),
];
