import { article } from "../article-factory.js";

export const INSTITUTIONS_EXPERIENCE_ARTICLES = [
  article({
    slug: "what-is-an-institution",
    categoryId: "institutions-experience",
    title: "What is an institution?",
    purpose: "What counts as an institution in Humanity Union?",
    overview:
      "An institution is an existing organization with public authority or responsibility — government bodies, agencies, councils, or recognized entities.",
    diagramId: "institution-levels",
    explanation: [
      {
        id: "definition",
        heading: "Definition",
        body: "Humanity Union does not create institutions. It documents how civic initiatives may reach them through delivery and response records.",
      },
    ],
    keyConcepts: ["Institution", "Authority", "Delivery"],
    relatedConceptSlugs: ["institution-levels", "civic-action-package"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 2,
    searchTerms: ["institution", "government", "organization"],
    assistantTags: ["institution"],
    sortOrder: 1,
  }),
  article({
    slug: "institution-levels",
    categoryId: "institutions-experience",
    title: "Institution levels",
    purpose: "What are local, regional, national, and international levels?",
    overview:
      "Institutions operate at different geographic and jurisdictional levels. CAP delivery targets the appropriate level.",
    diagramId: "institution-levels",
    explanation: [
      {
        id: "levels",
        heading: "Four levels",
        body: "Local institutions serve communities. Regional bodies coordinate provinces or states. National institutions set country-wide policy. International bodies address cross-border issues.",
      },
    ],
    keyConcepts: ["Local", "Regional", "National", "International"],
    relatedConceptSlugs: ["what-is-an-institution", "how-initiatives-reach-institutions"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 2,
    searchTerms: ["local", "regional", "national", "international"],
    assistantTags: ["institution"],
    sortOrder: 2,
  }),
  article({
    slug: "how-initiatives-reach-institutions",
    categoryId: "institutions-experience",
    title: "How initiatives reach institutions",
    purpose: "How does civic work connect to institutions?",
    overview:
      "After a collective decision, participants may issue a Civic Action Package and deliver it to selected recipients.",
    diagramId: "civic-pipeline",
    explanation: [
      {
        id: "path",
        heading: "Delivery path",
        body: "Initiative → Decision → CAP → Delivery → Official Response. Each step creates a public record.",
      },
    ],
    keyConcepts: ["CAP", "Delivery", "Recipient"],
    relatedConceptSlugs: ["civic-action-package", "how-delivery-works"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 3,
    searchTerms: ["reach", "institution", "delivery"],
    assistantTags: ["civic_action_package", "prepare_delivery_message"],
    sortOrder: 3,
  }),
  article({
    slug: "how-delivery-works",
    categoryId: "institutions-experience",
    title: "How Delivery works",
    purpose: "What happens when a CAP is delivered?",
    overview:
      "Delivery records who received a CAP, when, and through which mode. It does not guarantee institutional action.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "delivery",
        heading: "Delivery record",
        body: "Recipients and delivery status are logged. Public pages show delivery history linked to the CAP.",
      },
    ],
    keyConcepts: ["Delivery", "Recipient", "Status"],
    relatedConceptSlugs: ["civic-action-package", "official-response"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 2,
    searchTerms: ["delivery", "cap", "send"],
    assistantTags: ["prepare_delivery_message"],
    sortOrder: 4,
  }),
  article({
    slug: "how-official-responses-appear",
    categoryId: "institutions-experience",
    title: "How Official Responses appear",
    purpose: "How are institutional responses shown publicly?",
    overview: "Published official responses appear on public pages linked to CAPs and initiatives.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "public",
        heading: "Public appearance",
        body: "Responses include subject, type, and verification state. They are reference records, not platform opinions.",
      },
    ],
    keyConcepts: ["Official response", "Publication", "Verification"],
    relatedConceptSlugs: ["official-response"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 2,
    searchTerms: ["official response", "institution reply"],
    assistantTags: ["summarize_official_response"],
    sortOrder: 5,
  }),
  article({
    slug: "how-civic-accountability-works",
    categoryId: "institutions-experience",
    title: "How Civic Accountability works",
    purpose: "What is accountability after a response?",
    overview:
      "Accountability records track follow-up events when commitments or responses require continued attention.",
    diagramId: "process-flow",
    explanation: [
      {
        id: "accountability",
        heading: "Accountability events",
        body: "Participants may log events over time. Status reflects active follow-up, not legal enforcement.",
      },
    ],
    keyConcepts: ["Accountability", "Events", "Follow-up"],
    relatedConceptSlugs: ["civic-accountability"],
    relatedGuideSlugs: [],
    relatedPublicPageHrefs: [],
    readingTimeMinutes: 2,
    searchTerms: ["accountability", "follow-up"],
    assistantTags: ["prepare_accountability_event"],
    sortOrder: 6,
  }),
  article({
    slug: "how-public-archive-preserves-memory",
    categoryId: "institutions-experience",
    title: "How Public Archive preserves civic memory",
    purpose: "How does the archive preserve institutional interaction history?",
    overview:
      "Archive records bundle references to decisions, deliveries, responses, and impacts for long-term study.",
    diagramId: "reference-architecture",
    explanation: [
      {
        id: "memory",
        heading: "Civic memory",
        body: "Archives reference source records without replacing them. Researchers can trace full context from a single archive entry.",
      },
    ],
    keyConcepts: ["Archive", "References", "Memory"],
    relatedConceptSlugs: ["public-civic-archive"],
    relatedGuideSlugs: ["archive-experience"],
    relatedPublicPageHrefs: [{ title: "Civic Archive", href: "/civic-archive" }],
    readingTimeMinutes: 2,
    searchTerms: ["archive", "memory", "preserve"],
    assistantTags: ["prepare_archive_lessons"],
    sortOrder: 7,
  }),
];
