export const MONGO_COLLECTIONS = {
  initiatives: "initiatives",
  initiativeAnalyses: "initiative_analyses",
  initiativeImprovementProposals: "initiative_improvement_proposals",
  initiativeVersionRevisions: "initiative_version_revisions",
  initiativeRevisionDrafts: "initiative_revision_drafts",
  decisionSessions: "decision_sessions",
  initiativeCollectiveDecisions: "initiative_collective_decisions",
  initiativeDecisionVotes: "initiative_decision_votes",
  initiativeDecisionVoteHistory: "initiative_decision_vote_history",
  publicChoiceCandidates: "public_choice_candidates",
  publicChoiceResultsSnapshots: "public_choice_results_snapshots",
  participationAreas: "participation_areas",
  participationAreaTransitions: "participation_area_transitions",
  civicActionPackages: "civic_action_packages",
  civicDeliveries: "civic_deliveries",
  civicDeliveryRecipients: "civic_delivery_recipients",
  officialResponses: "official_responses",
  officialResponseIdentities: "official_response_identities",
  officialResponseMetadata: "official_response_metadata",
  civicAccountabilities: "civic_accountabilities",
  civicAccountabilityEvents: "civic_accountability_events",
  initiativeImplementationCommitments: "initiative_implementation_commitments",
  initiativeImplementationTrackings: "initiative_implementation_trackings",
  implementationTrackingUpdates: "implementation_tracking_updates",
  initiativePublicImpacts: "initiative_public_impacts",
  publicImpactEvidence: "public_impact_evidence",
  publicCivicArchiveRecords: "public_civic_archive_records",
  publicNewsArticles: "public_news_articles",
  mediaResources: "media_resources",
  countryAffiliations: "country_affiliations",
  civicCompatibilityReviews: "civic_compatibility_reviews",
  authUsers: "auth_users",
  authSessions: "auth_sessions",
  memberProfiles: "member_profiles",
  memberships: "memberships",
  membershipContributions: "membership_contributions",
  membershipWebhookEvents: "membership_webhook_events",
  memberBadgeContributions: "member_badge_contributions",
  memberBadgeApplications: "member_badge_applications",
  memberPreferences: "member_preferences",
  memberNotifications: "member_notifications",
  /** Pack 22E.1 — Admin Notification Center inbox (per-Admin projection rows). */
  adminNotifications: "admin_notifications",
  /** Pack 22E.3 — operational incident state (separate from visible inbox rows). */
  adminOperationalIncidents: "admin_operational_incidents",
  memberReminders: "member_reminders",
  emailAuditRecords: "email_audit_records",
  emailVerificationTokens: "email_verification_tokens",
  emailConfirmationCodes: "email_confirmation_codes",
  emailConfirmationSendLog: "email_confirmation_send_log",
  betaInvites: "beta_invites",
  /** Pack 24B — Participant suspension records (review token hash only; never raw token). */
  participantSuspensions: "participant_suspensions",
  initiativeComments: "initiative_comments",
  initiativeCommentReactions: "initiative_comment_reactions",
  initiativeAnalysisReactions: "initiative_analysis_reactions",
  initiativeSupportRegisteredSignals: "initiative_support_registered_signals",
  initiativeSupportVisitorSignals: "initiative_support_visitor_signals",
  initiativeSupportBookmarks: "initiative_support_bookmarks",
  initiativeSupportViews: "initiative_support_views",
  civicNominations: "civic_nominations",
  civicNominationVotes: "civic_nomination_votes",
  civicNominationVoteHistory: "civic_nomination_vote_history",
  civicNominationVotingSessions: "civic_nomination_voting_sessions",
  members: "members",
  activities: "activities",
  discussions: "discussions",
  proposals: "proposals",
  decisions: "decisions",
  petitions: "petitions",
  petitionSignatures: "petition_signatures",
  outbox: "outbox",
  processedEvents: "processed_events",
  workspaceProjections: "workspace_projections",
  participantActions: "participant_actions",
  initiativeAllies: "initiative_allies",
  initiativeDiscussionProposalCandidates: "initiative_discussion_proposal_candidates",
  directConversations: "direct_conversations",
  directMessages: "direct_messages",
  initiativeCollaborationChannelMessages: "initiative_collaboration_channel_messages",
  initiativeCollaborationChannelReads: "initiative_collaboration_channel_reads",
  initiativeCollaborationSessions: "initiative_collaboration_sessions",
  initiativeCollaborationSessionAttendances: "initiative_collaboration_session_attendances",
  sharedDocuments: "shared_documents",
  mediaUploadRecords: "media_upload_records",
  initiativeImprovementProposalsCollections: "initiative_improvement_proposals_collections",
  initiativeProposalReactions: "initiative_proposal_reactions",
  initiativeRevisionReactions: "initiative_revision_reactions",
  initiativePetitionDrafts: "initiative_petition_drafts",
  initiativeDiscussionCompletions: "initiative_discussion_completions",

  initiativeDecisionSessionDrafts: "initiative_decision_session_drafts",
  initiativeDecisionSessionRecommendations: "initiative_decision_session_recommendations",
  initiativeCollectiveDecisionLifecycleDrafts: "initiative_collective_decision_lifecycle_drafts",
  initiativeImplementationCommitmentLifecycleDrafts: "initiative_implementation_commitment_lifecycle_drafts",
  initiativeImplementationCommitmentPackages: "initiative_implementation_commitment_packages",
  initiativeImplementationTrackingLifecycleDrafts: "initiative_implementation_tracking_lifecycle_drafts",
  initiativeImplementationTrackingPackages: "initiative_implementation_tracking_packages",
  initiativeOfficialResponseLifecycleDrafts: "initiative_official_response_lifecycle_drafts",
  initiativeOfficialResponsePackages: "initiative_official_response_packages",
  initiativeOfficialResponsePackageRecords: "initiative_official_response_package_records",
  initiativePublicImpactLifecycleDrafts: "initiative_public_impact_lifecycle_drafts",
  initiativePublicImpactReports: "initiative_public_impact_reports",
  initiativeCivicArchiveLifecycleDrafts: "initiative_civic_archive_lifecycle_drafts",
  initiativeCivicArchiveVersions: "initiative_civic_archive_versions",
  petitionVisitorSignals: "petition_visitor_signals",
  contentTranslations: "content_translations",
  /** Pack 02B — Admin-managed Language Registry. */
  languageRegistry: "language_registry",
  /** Pack 02F — Canonical Terminology Glossary. */
  terminologyGlossary: "terminology_glossary",
  /** Pack 08I.2 — Admin-managed Brand Localization. */
  brandLocalization: "brand_localization",
  /** Pack 08I.5 — Admin-managed Legal Localization (counsel-approved). */
  legalLocalization: "legal_localization",
  blogPosts: "blog_posts",
  blogCategories: "blog_categories",
  blogSubscribers: "blog_subscribers",
  blogSubscriptionSettings: "blog_subscription_settings",
  /** Pack 21D — (postId, subscriberId) publication email delivery ledger. */
  blogPublicationDeliveries: "blog_publication_deliveries",
  /** Pack 21E — Admin selected-subscriber message records. */
  blogAdminSubscriberMessages: "blog_admin_subscriber_messages",
  /** Pack 21E — (adminMessageId, subscriberId) delivery ledger. */
  blogAdminSubscriberMessageDeliveries: "blog_admin_subscriber_message_deliveries",
  blogCapabilityGrants: "blog_capability_grants",
  blogAuthorApplications: "blog_author_applications",
  blogComments: "blog_comments",
  blogReactions: "blog_reactions",
  // Admin Foundation Pack 02 — generalized grants + append-only audit.
  platformCapabilityGrants: "platform_capability_grants",
  administrationAuditLog: "administration_audit_log",
  // Pack 11C — first-party traffic analytics (stable names; 90d event TTL).
  trafficEvents: "traffic_events",
  trafficSessions: "traffic_sessions",
  // Pack 11D — long-lived daily aggregates + opaque visitor first-seen registry.
  trafficDailyAggregates: "traffic_daily_aggregates",
  trafficVisitorRegistry: "traffic_visitor_registry",
  // Pack 12A — delegated Editor grants (one record per Participant).
  editorGrants: "editor_grants",
  // Pack 17C — canonical Admin-managed official social account URLs (no credentials).
  platformSocialAccounts: "platform_social_accounts",
  // Production Completion Pack 01 — Admin-managed Support operational links (URLs only).
  platformSupportLinks: "platform_support_links",
  // SEO Pack 07 — sparse Admin page SEO overrides (non-Blog public pages).
  seoPageOverrides: "seo_page_overrides",
} as const;

export type MongoCollectionName = (typeof MONGO_COLLECTIONS)[keyof typeof MONGO_COLLECTIONS];
