export const MONGO_COLLECTIONS = {
  initiatives: "initiatives",
  initiativeAnalyses: "initiative_analyses",
  initiativeImprovementProposals: "initiative_improvement_proposals",
  initiativeVersionRevisions: "initiative_version_revisions",
  initiativeRevisionDrafts: "initiative_revision_drafts",
  decisionSessions: "decision_sessions",
  initiativeCollectiveDecisions: "initiative_collective_decisions",
  initiativeDecisionVotes: "initiative_decision_votes",
  initiativeDecisionVoteHistory: "initiative_decision_vote_history",
  participationAreas: "participation_areas",
  participationAreaTransitions: "participation_area_transitions",
  civicActionPackages: "civic_action_packages",
  civicDeliveries: "civic_deliveries",
  civicDeliveryRecipients: "civic_delivery_recipients",
  officialResponses: "official_responses",
  officialResponseIdentities: "official_response_identities",
  officialResponseMetadata: "official_response_metadata",
  civicAccountabilities: "civic_accountabilities",
  civicAccountabilityEvents: "civic_accountability_events",
  initiativeImplementationCommitments: "initiative_implementation_commitments",
  initiativeImplementationTrackings: "initiative_implementation_trackings",
  implementationTrackingUpdates: "implementation_tracking_updates",
  initiativePublicImpacts: "initiative_public_impacts",
  publicImpactEvidence: "public_impact_evidence",
  publicCivicArchiveRecords: "public_civic_archive_records",
  civicCompatibilityReviews: "civic_compatibility_reviews",
} as const;

export type MongoCollectionName = (typeof MONGO_COLLECTIONS)[keyof typeof MONGO_COLLECTIONS];
